name: "linux-build-deploy-web"
on:
  push:
    branches:
      - master
    paths-ignore:
    #   - .github/workflows/pub_web.yml
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      acc_volcan_id: ${{ secrets.ACC_VOLCAN_ID }}
      acc_volcan_key: ${{ secrets.ACC_VOLCAN_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          # If using the 'assets' git submodule from Chirpy Starter, uncomment above
          # (See: https://github.com/cotes2020/chirpy-starter/tree/main/assets)
      - name: checkout ffmpeg source and build docs
        run: |
            git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
            cd ffmpeg
            git checkout release/7.1
            echo "ffmpeg version: $(git rev-parse HEAD)"
            ls -al
            git submodule update --init --recursive
            cd .. && pwd
            chmod +x ./ffmpeg/configure
            bash ./generate-doc.sh ../ffmpeg

      - name: Setup Node.js #node js 上传搜索数据
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install node dependencies
        run: |
            npm install -g
            make
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python ./tranlate.py volcan ${{env.acc_volcan_id}} ${{env.acc_volcan_key}}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: htdocs_cn
      

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
