name: "linux-publish_web_site"
on:
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #   #   - .github/workflows/pub_web.yml
  #     - .gitignore
  #     - README.md
  #     - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: linjonh/ffmpeg-docs-website
          token: ${{ secrets.PAT_TOKEN }}
          path: docs_
            
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs_/ffmpeg-docs_volcan_translate
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
